#ifndef HAMMER_SERVER_STATUS_H_
#define HAMMER_SERVER_STATUS_H_

enum server_status {
	SERVER_STATUS_UNKNOWN,
	SERVER_STATUS_AWAITING_CONFIG,
	SERVER_STATUS_PLANET_GENERATION
};

#endif /* HAMMER_SERVER_STATUS_H_ */
