#ifndef HAMMER_SERVER_STATUS_H_
#define HAMMER_SERVER_STATUS_H_

enum server_status {
	SERVER_STATUS_UNKNOWN,
	SERVER_STATUS_CONFIG,
	SERVER_STATUS_GENERATION,
	SERVER_STATUS_RUNNING
};

#endif /* HAMMER_SERVER_STATUS_H_ */
