#ifndef HAMMER_CLIENT_APPSTATE_TRANSITIONS_H_
#define HAMMER_CLIENT_APPSTATE_TRANSITIONS_H_

enum {
	CLIENT_APPSTATE_TRANSITION_MAIN_MENU_CLOSE,
	CLIENT_APPSTATE_TRANSITION_LAUNCH_LOCAL_SERVER
};

#endif /* HAMMER_CLIENT_APPSTATE_TRANSITIONS_H_ */
