#ifndef HAMMER_CLIENT_APPSTATE_TRANSITION_TABLE_H_
#define HAMMER_CLIENT_APPSTATE_TRANSITION_TABLE_H_

#include "hammer/appstate.h"

enum {
	CLIENT_APPSTATE_TRANSITION_MAIN_MENU_OPEN = APPSTATE_STATE_INITIAL,
	CLIENT_APPSTATE_TRANSITION_DISCOVER_SERVER,
	CLIENT_APPSTATE_TRANSITION_MAIN_MENU_CLOSE = APPSTATE_STATE_TERMINATE
};

extern size_t client_tt_sz;
extern struct appstate_transition client_tt[];

extern struct appstate_manager client_appstate_mgr;

#endif /* HAMMER_CLIENT_APPSTATE_TRANSITIONS_H_ */
