#ifndef HAMMER_SERVER_APPSTATE_TRANSITION_TABLE_H_
#define HAMMER_SERVER_APPSTATE_TRANSITION_TABLE_H_

#include "hammer/appstate.h"

enum {
	SERVER_APPSTATE_TRANSITION_START_LOCAL = APPSTATE_STATE_INITIAL,
	SERVER_APPSTATE_TRANSITION_LISTEN_CONFIG,
	SERVER_APPSTATE_TRANSITION_GENERATION,
	SERVER_APPSTATE_TRANSITION_RUNNING,
	SERVER_APPSTATE_TRANSITION_SHUTDOWN = APPSTATE_STATE_TERMINATE
};

extern size_t local_server_tt_sz;
extern struct appstate_transition local_server_tt[];

extern struct appstate_manager server_appstate_mgr;

#endif /* HAMMER_SERVER_APPSTATE_TRANSITION_TABLE_H_ */
